import { describe, expect, it } from 'vitest'

import {
  assertAllowedStatus,
  assertNoChallengeText,
  CollectorBlockedError,
} from './policy'

describe('Collector stop policy', () => {
  it.each([403, 429])('stops immediately on HTTP %s', (status) => {
    expect(() => assertAllowedStatus(status, 'https://example.test')).toThrow(
      CollectorBlockedError,
    )
  })

  it('stops on a CAPTCHA or WAF challenge instead of continuing', () => {
    expect(() =>
      assertNoChallengeText(
        'Verify you are human - CAPTCHA',
        'https://example.test',
      ),
    ).toThrow(CollectorBlockedError)
  })

  it('stops on a CloudFront 403 page when a popup response is unavailable', () => {
    expect(() =>
      assertNoChallengeText(
        '403 ERROR\nThe request could not be satisfied.\nRequest blocked.\nGenerated by cloudfront (CloudFront)',
        'https://decklog.bushiroad.com/view/ABCDE',
      ),
    ).toThrow(CollectorBlockedError)
  })

  it('does not treat an ordinary public page as blocked', () => {
    expect(() =>
      assertNoChallengeText('大会結果発表', 'https://example.test'),
    ).not.toThrow()
  })
})
